"""Initial migration

Revision ID: c25053d1b726
Revises: 
Create Date: 2026-03-16 00:57:41.872982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c25053d1b726'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='uq_connection_sender_receiver')
    )
    op.create_index(op.f('ix_connection_requests_id'), 'connection_requests', ['id'], unique=False)
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_user_registration')
    )
    op.create_index(op.f('ix_event_registrations_id'), 'event_registrations', ['id'], unique=False)
    op.create_table('investor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_name', sa.String(length=180), nullable=False),
    sa.Column('interests', sa.Text(), nullable=False),
    sa.Column('funding_range', sa.Float(), nullable=False),
    sa.Column('preferred_industries', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_profiles_id'), 'investor_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_investor_profiles_investor_name'), 'investor_profiles', ['investor_name'], unique=False)
    op.create_table('startup_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startup_name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('pitch_deck_url', sa.String(length=255), nullable=True),
    sa.Column('founders', sa.Text(), nullable=False),
    sa.Column('funding_needed', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_profiles_id'), 'startup_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_startup_profiles_industry'), 'startup_profiles', ['industry'], unique=False)
    op.create_index(op.f('ix_startup_profiles_stage'), 'startup_profiles', ['stage'], unique=False)
    op.create_index(op.f('ix_startup_profiles_startup_name'), 'startup_profiles', ['startup_name'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_deck_id', sa.Integer(), nullable=True),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('problem_clarity', sa.Float(), nullable=True),
    sa.Column('market_size', sa.Float(), nullable=True),
    sa.Column('product_differentiation', sa.Float(), nullable=True),
    sa.Column('traction', sa.Float(), nullable=True),
    sa.Column('team_strength', sa.Float(), nullable=True),
    sa.Column('financial_potential', sa.Float(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('evidence_map', sa.Text(), nullable=True),
    sa.Column('dashboard_insights', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pitch_deck_id'], ['pitch_decks.id'], ),
    sa.ForeignKeyConstraint(['startup_id'], ['startup_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_id'), 'ai_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_pitch_deck_id'), 'ai_analyses', ['pitch_deck_id'], unique=False)
    op.create_table('ai_analysis_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_chunks_analysis_id'), 'ai_analysis_chunks', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_chunks_id'), 'ai_analysis_chunks', ['id'], unique=False)
    op.create_table('investor_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['investor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investor_recommendations_analysis_id'), 'investor_recommendations', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_investor_recommendations_id'), 'investor_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_investor_recommendations_investor_id'), 'investor_recommendations', ['investor_id'], unique=False)
    op.create_index(op.f('ix_investor_recommendations_match_score'), 'investor_recommendations', ['match_score'], unique=False)
    op.drop_index(op.f('idx_startups_industry'), table_name='startups')
    op.drop_index(op.f('idx_startups_stage'), table_name='startups')
    op.drop_table('startups')
    op.drop_table('activity_logs')
    op.drop_index(op.f('idx_matches_startup'), table_name='investor_matches')
    op.drop_table('investor_matches')
    op.drop_table('evaluations')
    op.drop_index(op.f('idx_investors_stage'), table_name='investors')
    op.drop_table('investors')
    op.add_column('events', sa.Column('organizer_name', sa.String(length=180), nullable=False))
    op.add_column('events', sa.Column('capacity', sa.Integer(), nullable=False))
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=180),
               nullable=False)
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('events', 'location',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=180),
               nullable=False)
    op.alter_column('events', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.drop_column('events', 'max_attendees')
    op.drop_column('events', 'organizer')
    op.add_column('pitch_decks', sa.Column('file_name', sa.String(length=255), nullable=False))
    op.add_column('pitch_decks', sa.Column('file_path', sa.String(length=255), nullable=False))
    op.add_column('pitch_decks', sa.Column('status', sa.String(length=32), nullable=False))
    op.alter_column('pitch_decks', 'startup_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pitch_decks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_pitch_decks_id'), 'pitch_decks', ['id'], unique=False)
    op.create_index(op.f('ix_pitch_decks_startup_id'), 'pitch_decks', ['startup_id'], unique=False)
    op.create_index(op.f('ix_pitch_decks_status'), 'pitch_decks', ['status'], unique=False)
    op.drop_constraint(op.f('pitch_decks_startup_id_fkey'), 'pitch_decks', type_='foreignkey')
    op.create_foreign_key(None, 'pitch_decks', 'startup_profiles', ['startup_id'], ['id'])
    op.drop_column('pitch_decks', 'suggestions')
    op.drop_column('pitch_decks', 'file_url')
    op.drop_column('pitch_decks', 'missing_sections')
    op.drop_column('pitch_decks', 'pitch_score')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('users', 'hashed_password')
    op.add_column('pitch_decks', sa.Column('pitch_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitch_decks', sa.Column('missing_sections', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pitch_decks', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pitch_decks', sa.Column('suggestions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch_decks', type_='foreignkey')
    op.create_foreign_key(op.f('pitch_decks_startup_id_fkey'), 'pitch_decks', 'startups', ['startup_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pitch_decks_status'), table_name='pitch_decks')
    op.drop_index(op.f('ix_pitch_decks_startup_id'), table_name='pitch_decks')
    op.drop_index(op.f('ix_pitch_decks_id'), table_name='pitch_decks')
    op.alter_column('pitch_decks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('pitch_decks', 'startup_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('pitch_decks', 'status')
    op.drop_column('pitch_decks', 'file_path')
    op.drop_column('pitch_decks', 'file_name')
    op.add_column('events', sa.Column('organizer', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('max_attendees', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('events', 'event_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('events', 'location',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('events', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('events', 'title',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('events', 'capacity')
    op.drop_column('events', 'organizer_name')
    op.create_table('investors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('firm', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('investment_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferred_industries', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('ticket_size', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('investors_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('investors_pkey'))
    )
    op.create_index(op.f('idx_investors_stage'), 'investors', ['investment_stage'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('startup_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('market_potential', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_strength', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('investment_readiness', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strengths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggestions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('evaluations_startup_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('evaluations_pkey'))
    )
    op.create_table('investor_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('startup_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('investor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('match_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], name=op.f('investor_matches_investor_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], name=op.f('investor_matches_startup_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('investor_matches_pkey'))
    )
    op.create_index(op.f('idx_matches_startup'), 'investor_matches', ['startup_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('activity_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('activity_logs_pkey'))
    )
    op.create_table('startups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('founder_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('startup_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('traction_metrics', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('funding_needed', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pitch_deck_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], name=op.f('startups_founder_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('startups_pkey'))
    )
    op.create_index(op.f('idx_startups_stage'), 'startups', ['stage'], unique=False)
    op.create_index(op.f('idx_startups_industry'), 'startups', ['industry'], unique=False)
    op.drop_index(op.f('ix_investor_recommendations_match_score'), table_name='investor_recommendations')
    op.drop_index(op.f('ix_investor_recommendations_investor_id'), table_name='investor_recommendations')
    op.drop_index(op.f('ix_investor_recommendations_id'), table_name='investor_recommendations')
    op.drop_index(op.f('ix_investor_recommendations_analysis_id'), table_name='investor_recommendations')
    op.drop_table('investor_recommendations')
    op.drop_index(op.f('ix_ai_analysis_chunks_id'), table_name='ai_analysis_chunks')
    op.drop_index(op.f('ix_ai_analysis_chunks_analysis_id'), table_name='ai_analysis_chunks')
    op.drop_table('ai_analysis_chunks')
    op.drop_index(op.f('ix_ai_analyses_pitch_deck_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_startup_profiles_startup_name'), table_name='startup_profiles')
    op.drop_index(op.f('ix_startup_profiles_stage'), table_name='startup_profiles')
    op.drop_index(op.f('ix_startup_profiles_industry'), table_name='startup_profiles')
    op.drop_index(op.f('ix_startup_profiles_id'), table_name='startup_profiles')
    op.drop_table('startup_profiles')
    op.drop_index(op.f('ix_investor_profiles_investor_name'), table_name='investor_profiles')
    op.drop_index(op.f('ix_investor_profiles_id'), table_name='investor_profiles')
    op.drop_table('investor_profiles')
    op.drop_index(op.f('ix_event_registrations_id'), table_name='event_registrations')
    op.drop_table('event_registrations')
    op.drop_index(op.f('ix_connection_requests_id'), table_name='connection_requests')
    op.drop_table('connection_requests')
    # ### end Alembic commands ###
